### ISSUE TITLE
LookupError is being raised when running the docker container

### ISSUE THREAD

**Issue by K44Z** [Xilinx/logicnets#13]
Hello, 
When I try to run the container through the command ./docker/run-docker.sh a LookupError is being raised after all 33 steps were successfully executed.

 the full error log can be found here: https://pastebin.com/rn18q61A

please note that although the environment variable VIVADO_SETTINGS_FILE has already been set to point to the vivado settings64.sh file, I am still receiving the following message: 
($VIVADO_SETTINGS_FILE not defined. Please set VIVADO_SETTINGS_FILE to point to the location of settings64.sh in your Vivado installation, if you want to synthesize your networks.) 

my environment: My environment: Ubuntu 18.04.4 LTS , Vivado design suite 2020.1

**Comment by nickfraser** [comment]
This looks like an issue with one of the dependencies - I may have to pin the version number. Let me look into this and get back to you.

**Comment by nickfraser** [comment]
> the full error log can be found here: https://pastebin.com/rn18q61A

I'm unable to reproduce this error locally. On a closer inspection, the error is in determining the version number of LogicNets. Pip uses tags in the git repository to determine the version number, so this is likely due to your local logicnets git repo being corrupted. Can you try a fresh clone of the logicnets repo? Note, you do need to have the `.git` folder within logicnets for this to work.

> please note that although the environment variable VIVADO_SETTINGS_FILE has already been set to point to the vivado settings64.sh file, I am still receiving the following message:

I'm having no issues with this either. How are you setting the environment variable? You'll notice this is a standard, basic check for an environment variable in `bash` within [`run_docker.sh`](https://github.com/Xilinx/logicnets/blob/master/docker/run-docker.sh#L41-L49). Are you sure you're spelling/setting the variable correctly?

**Comment by K44Z** [comment]
thank you for your response.
after recloning the repo, the docker container ran fine with no problems.

about creating the environment variable, it was successfully defined using the command line: 
export VIVADO_SETTINGS_FILE=/path/to/Vivado/settings64.sh
the path to the settings64.sh file was successfully mounted inside the docker container. looks like I misspelled it before. 

Thanks for the help. really appreciate it.

**Comment by nickfraser** [comment]
No problems
